### ISSUE TITLE
Feature request - Save image as PNG for better visual quality and smaller file size

### ISSUE THREAD

**Issue by o-l-a-v** [msandbu/azuread#1]
Lossless image formats, like PNG or WebP in lossless mode, are more suitable for storing computer generated graphics and text than lossy formats like JPG. It will both be lossless (no visual artifacts), and likely be smaller in file size, compared to JPG. One could also losslessly squeeze out some extra bytes with tools like [pinga](https://css-ig.net/pinga).

Exporting the diagram as SVG (vector graphics) would be even better. Maybe do both SVG and PNG?

**Comment by msandbu** [comment]
Thanks for the feedback! working on a new iteration now which includes some updated references and endpoint where I will also add the visio source and a new formats as well.

**Comment by msandbu** [comment]
Fixed, new content will be uploaded to github EOD
